# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    build: . 
    image: jocsakesley/logistics:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db
  db:
    image: postgres:17.2
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
