name: Deploy to EC2

on:
  push:
    branches: [ feature/deployment ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_DNS: ec2-54-90-67-241.compute-1.amazonaws.com
  REMOTE_USER: ec2-user

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::398306423585:role/github-actions-role'
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/logistics_api.pem
          chmod 600 ~/.ssh/logistics_api.pem
      
      - name: Create deployment package
        run: |
          tar -czf app.tar.gz ./* 
            
      - name: Copy files to EC2
        run: |
            ssh -i ~/.ssh/logistics_api.pem ${{ env.REMOTE_USER }}@${{ env.EC2_INSTANCE_DNS }} 'mkdir -p ~/app'
            scp app.tar.gz ${{ env.REMOTE_USER }}@${{ env.EC2_INSTANCE_DNS }}:~/app/
            ssh ${{ env.REMOTE_USER }}@${{ env.EC2_INSTANCE_DNS }} '
            cd ~/app
            tar -xzf app.tar.gz
            rm app.tar.gz
            '

      - name: Deploy application
        run: |
            ssh ${{ env.REMOTE_USER }}@${{ env.EC2_INSTANCE_DNS }} '
                cd ~/app
                sudo docker-compose down
                sudo docker-compose build --no-cache api
                sudo docker-compose up -d
            '